repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        types: [ file ]
        files: \.(ts)$
        args: [--maxkb=100]
        exclude: '^yarn\.lock$'
      - id: check-json
        exclude: '^tsconfig.run.json$'
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: build
        name: build
        entry: bash -c 'make build'
        language: system
      - id: clean
        name: clean
        entry: bash -c 'make clean'
        language: system
      - id: lint
        name: lint
        entry: make lint-fix
        language: system
        types: [ file ]
        files: \.(ts)$
      - id: test
        name: test
        entry: bash -c 'make test'
        language: system
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]
