repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=100]
        exclude: '^yarn\.lock$'
      - id: check-json
        exclude: '^tsconfig.run.json$'
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: yarn-build
        name: yarn build
        entry: bash -c 'yarn build'
        language: system
      - id: yarn-clean
        name: yarn clean
        entry: bash -c 'rm -rf dist'
        language: system
      - id: yarn-lint
        name: yarn lint
        entry: yarn lint
        language: system
        types: [ file ]
        files: \.(ts)$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]
